#!/usr/bin/env Rscript
source("config.R")

webservice <- "eupathdb"

meta <- download_eupathdb_metadata(bioc_version = bioc_version, overwrite = TRUE,
                                 webservice = webservice, verbose = TRUE, # 
                                 eu_version = eu_version, write_csv = TRUE)

message("Finished downloading metadata...")
message(sprintf("Found: %d valid / %d invalid (missing taxonomy id)",
                nrow(meta$valid), nrow(meta$invalid)))

message("Invalid entries:")
print(meta$invalid$SourceUrl)

all_metadata <- meta[["valid"]]

for (i in 1:nrow(all_metadata)) {
  entry <- all_metadata[i, ]
  species <- entry[["Species"]]

  message("Starting generation of ", species, " (", i, "/", nrow(all_metadata), ")")

  pkgnames <- get_eupathdb_pkgnames(entry)

  if (isTRUE(bsgenome)) {
    bsgenome_result <- make_eupathdb_bsgenome(entry, eu_version = eu_version, copy_s3 = TRUE)
    expected <- "bsgenome_name"
    actual <- names(bsgenome_result)
    testthat::test_that("Does make_eupathdb_bsgenome return something sensible?", {
      expect_equal(expected, actual)
    })
    results[["bsgenome"]][[species]] <- bsgenome_result
  }
  if (isTRUE(orgdb)) {
    #
    # some harmless warnings are likely to be encountered.
    #
    # Warning arises from AnnotationForge::makeOrgPackage():
    #
    #   In result_fetch(res@ptr, n = n):
    #   SQL statements must be issued with dbExecute() or dbSendStatement() instead of dbGetQuery() or dbSendQuery().
    #   Calls: make_eupathdb_orgdb ... .createMetadataTables -> dbGetQuery -> dbGetQuery -> .local -> dbFetch -> dbFetch -> .local -> result_fe
    #
    # Warning generated by post_eupathdb_raw():
    #
    #   In post_eupathdb_raw(entry, question = question, parameters = parameters,  ... :                                                █
    #   The provided species does not have a table of weights.    
    #
    orgdb_result <- make_eupathdb_orgdb(entry, copy_s3 = TRUE)

    if (is.null(orgdb_result)) {
      message("There is insufficient data for ", species, " to make the OrgDB.")
    } else {
      actual <- orgdb_result[["orgdb_name"]]
      expected <- pkgnames[["orgdb"]]
      test_that("Does make_eupathdb_orgdb return something sensible?", {
        expect_equal(expected, actual)
      })
      results[["orgdb"]][[species]] <- orgdb_result
    }
  }
  if (isTRUE(txdb)) {
    txdb_result <- make_eupathdb_txdb(entry, eu_version = eu_version, copy_s3 = TRUE)
    if (is.null(txdb_result)) {
      message("Unable to create the txdb package.")
    } else {
      actual <- txdb_result[["txdb_name"]]
      expected <- pkgnames[["txdb"]]
      test_that("Does make_eupathdb_txdb return something sensible?", {
        expect_equal(expected, actual)
      })
      results[["txdb"]][[species]] <- txdb_result[["txdb_name"]]
    }
  }
  if (isTRUE(organdb)) {
    organ_result <- make_eupathdb_organismdbi(entry, eu_version = eu_version, copy_s3 = TRUE)
    actual <- organ_result[["organdb_name"]]
    expected <- pkgnames[["organismdbi"]]
    test_that("Does make_eupathdb_organismdbi return something sensible?", {
      expect_equal(expected, actual)
    })
    results[["organismdbi"]] <- organ_result
  }
} ## End iterating over every entry in the eupathdb metadata.

## check_csv checks each metadata csv file to see that the files exist.
## check_files checks the list of files in each directory to see that they all have
## entries in the csv.
if (isTRUE(bsgenome)) {
  bs_csv <- check_csv(file_type = "BSgenome", bioc_version = bioc_version, eu_version = eu_version)
  bs_files <- check_files("BSgenome", bioc_version = bioc_version, eu_version = eu_version)
  csv_copy_path <- file.path(path.package("EuPathDB"), "inst", "extdata", bs_csv)
  copied <- file.copy(bs_csv, csv_copy_path)
  expect_true(copied)
  bs_checked <- AnnotationHubData::makeAnnotationHubMetadata(path.package("EuPathDB"), bs_csv)
  save(list = c("bs_checked"), file = "bsgenome_metadata.rda")
}
if (isTRUE(orgdb)) {
  org_csv <- check_csv(file_type = "OrgDb", bioc_version = bioc_version, eu_version = eu_version)
  org_files <- check_files("OrgDb", bioc_version = bioc_version, eu_version = eu_version)
  csv_copy_path <- file.path(path.package("EuPathDB"), "inst", "extdata", org_csv)
  copied <- file.copy(org_csv, csv_copy_path)
  expect_true(copied)
  org_checked <- AnnotationHubData::makeAnnotationHubMetadata(path.package("EuPathDB"), org_csv)
  save(list = c("org_checked"), file = "orgdb_metadata.rda")
}
if (isTRUE(txdb)) {
  txdb_csv <- check_csv(file_type = "TxDb", bioc_version = bioc_version, eu_version = eu_version)
  tx_files <- check_files("TxDb", bioc_version = bioc_version, eu_version = eu_version)
  csv_copy_path <- file.path(path.package("EuPathDB"), "inst", "extdata", txdb_csv)
  copied <- file.copy(txdb_csv, csv_copy_path)
  expect_true(copied)
  tx_checked <- AnnotationHubData::makeAnnotationHubMetadata(path.package("EuPathDB"), txdb_csv)
  save(list = c("tx_checked"), file = "txdb_metadata.rda")
}
if (isTRUE(organdb)) {
  organ_csv <- check_csv(file_type = "OrganismDbi", bioc_version = bioc_version, eu_version = eu_version)
  organ_files <- check_files("OrganismDbi", bioc_version = bioc_version, eu_version = eu_version)
  csv_copy_path <- file.path(path.package("EuPathDB"), "inst", "extdata", organ_csv)
  copied <- file.copy(organ_csv, csv_copy_path)
  expect_true(copied)
  organ_checked <- AnnotationHubData::makeAnnotationHubMetadata(path.package("EuPathDB"), organ_csv)
  save(list = c("organ_checked"), file = "organdb_metadata.rda")
}
if (isTRUE(granges)) {
  grange_csv <- check_csv(file_type = "GRanges", bioc_version = bioc_version, eu_version = eu_version)
  grange_files <- check_files("GRanges", bioc_version = bioc_version, eu_version = eu_version)
  csv_copy_path <- file.path(path.package("EuPathDB"), "inst", "extdata", grange_csv)
  copied <- file.copy(grange_csv, csv_copy_path)
  expect_true(copied)
  grange_checked <- AnnotationHubData::makeAnnotationHubMetadata(path.package("EuPathDB"), grange_csv)
  save(list = c("grange_checked"), file = "granges_metadata.rda")
}
